### ISSUE TITLE
你好，前端运行报错，这个10.100.100.246怎么去掉呢

### ISSUE THREAD

**Issue by 1049759078** [YoLoveLife/devEopsWeb#14]
C:\Users\n\Desktop\devEopsWeb>npm run dev

> deveopsweb@1.0.0 dev C:\Users\niejichao\Desktop\devEopsWeb
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js --host 10.100.100.246

 10% building modules 1/1 modules 0 activeevents.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 10.100.100.246:8080
    at Server.setupListenHandle [as _listen2] (net.js:1325:19)
    at listenInCluster (net.js:1383:12)
    at doListen (net.js:1498:7)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
Emitted 'error' event at:
    at emitErrorNT (net.js:1362:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    [... lines matching original stack trace ...]
    at bootstrap_node.js:666:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deveopsweb@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js --host 10.100.100.246`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deveopsweb@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\niejichao\AppData\Roaming\npm-cache\_logs\2018-06-30T04_47_08_162Z-debug.log

**Comment by YoLoveLife** [comment]
你在
[package.json](https://github.com/YoLoveLife/devEopsWeb/blob/master/package.json)
中将--host 去掉即可
并且
[request.js](https://github.com/YoLoveLife/devEopsWeb/blob/master/src/utils/request.js)
中也包含了这个地址
这个是我测试环境下的API地址
下几个版本会考虑把这个地址封装到外面修改

**Comment by 1049759078** [comment]
谢谢，解决了
